name: Open URL Locally

on:
  workflow_dispatch:

jobs:
  open-url:
    runs-on: self-hosted
    steps:
      - name: Open URL in Chrome
        shell: powershell
        run: |
         Start-Process "chrome.exe" -ArgumentList "https://webportal.wm.com/"
          Start-Sleep -Seconds 9
         
