name: E2E - Select dropdowns and start (Selenium Python)

on:
  workflow_dispatch:
    inputs:
      testUrl:
        description: "Target page URL"
        required: true
        default: "https://webportal.wm.com/"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Selenium
        run: pip install selenium==4.*

      - name: Run script
        env:
          TEST_URL: ${{ github.event.inputs.testUrl }}
        run: python ./scripts/selenium_custom_dropdown.py
